import type { Metadata } from "next";
import LegalLayout from "@/components/landing/Legal/LegalLayout";

export const metadata: Metadata = {
  title: "Terms of Service — ORQ8",
  description:
    "ORQ8 Terms of Service. Read the terms governing your use of the ORQ8 platform.",
};

export default function TermsPage() {
  return (
    <LegalLayout
      title="Terms of Service"
      lastUpdated="September 8, 2026"
    >
      <section>
        <h2>1. Acceptance of Terms</h2>
        <p>
          By accessing or using the ORQ8 platform (the &quot;Service&quot;), you agree
          to be bound by these Terms of Service (&quot;Terms&quot;). If you do not agree
          to these Terms, do not use the Service.
        </p>
        <p>
          These Terms constitute a legally binding agreement between you (&quot;you,&quot;
          &quot;your,&quot; or &quot;Founder&quot;) and ORQ8 (&quot;we,&quot; &quot;us,&quot;
          or &quot;our&quot;).
        </p>
      </section>

      <section>
        <h2>2. Description of Service</h2>
        <p>
          ORQ8 is an AI-powered organization operating system. The Service provides:
        </p>
        <ul>
          <li>An Executive Agent that understands your company and helps you manage it</li>
          <li>AI employees that can perform work on your behalf within configured boundaries</li>
          <li>Organizational management tools (departments, teams, goals, tasks, strategy)</li>
          <li>Workforce intelligence, performance analytics, and ROI tracking</li>
          <li>Decision memory and organizational knowledge management</li>
          <li>Integration capabilities with third-party services</li>
        </ul>
      </section>

      <section>
        <h2>3. Account Registration</h2>
        <ul>
          <li>You must be at least 18 years old to create an account</li>
          <li>You must provide accurate and complete registration information</li>
          <li>You are responsible for maintaining the security of your account credentials</li>
          <li>You must notify us immediately of any unauthorized use of your account</li>
          <li>One person or entity may not maintain more than one free account</li>
        </ul>
      </section>

      <section>
        <h2>4. Acceptable Use</h2>
        <p>You agree NOT to use the Service to:</p>
        <ul>
          <li>Violate any applicable law, regulation, or third-party rights</li>
          <li>Create AI employees or agents that generate harmful, illegal, or deceptive content</li>
          <li>Attempt to circumvent security features, access controls, or authorization systems</li>
          <li>Perform prompt injection or manipulate the Executive Agent to bypass governance</li>
          <li>Use the Service to develop competing products or services</li>
          <li>Reverse engineer, decompile, or disassemble any part of the Service</li>
          <li>Transmit malware, viruses, or other malicious code</li>
          <li>Overload or attempt to disrupt the Service infrastructure</li>
          <li>Use automated tools to access the Service in violation of these Terms</li>
          <li>Impersonate another person or entity</li>
          <li>Resell or redistribute the Service without written authorization</li>
        </ul>
      </section>

      <section>
        <h2>5. Your Data</h2>
        <h3>5.1 Ownership</h3>
        <p>
          You retain all rights, title, and interest in your data. We do not claim
          ownership over any content, organizational data, or AI-generated outputs
          created through the Service.
        </p>

        <h3>5.2 License to Process</h3>
        <p>
          By using the Service, you grant us a limited license to process your data
          solely for the purpose of providing and improving the Service. This license
          terminates when you delete your data or close your account.
        </p>

        <h3>5.3 AI-Generated Content</h3>
        <p>
          Content generated by AI employees and the Executive Agent using the Service
          is owned by you. However, similar or identical content may be generated for
          other users through independent AI processing. We do not guarantee
          uniqueness of AI-generated content.
        </p>

        <h3>5.4 Data Portability</h3>
        <p>
          You can export your organizational data at any time through the Service.
          Upon account closure, we will provide a reasonable export window.
        </p>
      </section>

      <section>
        <h2>6. AI Employee Governance</h2>
        <ul>
          <li>You are responsible for configuring appropriate autonomy levels for your AI employees</li>
          <li>You are responsible for setting approval requirements for sensitive operations</li>
          <li>ORQ8 enforces governance rules server-side, but you must configure them appropriately</li>
          <li>AI employees operate within the boundaries you define — ORQ8 does not override your governance settings</li>
          <li>You are liable for the actions of your AI employees when they operate within your authorized parameters</li>
        </ul>
      </section>

      <section>
        <h2>7. Payments and Subscriptions</h2>
        <ul>
          <li>The Service is offered through subscription plans with varying features and limits</li>
          <li>Free trial periods, if offered, convert to paid subscriptions unless cancelled before the trial ends</li>
          <li>Subscription fees are billed in advance on a recurring basis</li>
          <li>All fees are non-refundable except as required by applicable law</li>
          <li>We reserve the right to change pricing with 30 days&apos; notice</li>
          <li>Work credits and AI employee usage are subject to plan limits</li>
        </ul>
      </section>

      <section>
        <h2>8. Intellectual Property</h2>
        <ul>
          <li>The Service, including its design, code, and features, is owned by ORQ8</li>
          <li>You receive a limited, non-exclusive, non-transferable license to use the Service</li>
          <li>You may not copy, modify, distribute, sell, or lease any part of the Service</li>
          <li>ORQ8 trademarks, logos, and brand elements may not be used without written permission</li>
        </ul>
      </section>

      <section>
        <h2>9. Third-Party Integrations</h2>
        <ul>
          <li>The Service may integrate with third-party platforms and services</li>
          <li>Your use of third-party services is governed by their respective terms</li>
          <li>We are not responsible for the availability, accuracy, or practices of third-party services</li>
          <li>You authorize us to interact with third-party services on your behalf when you enable integrations</li>
        </ul>
      </section>

      <section>
        <h2>10. Disclaimers</h2>
        <p>
          THE SERVICE IS PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; WITHOUT
          WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
          TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,
          AND NON-INFRINGEMENT.
        </p>
        <p>
          We do not guarantee that the Service will be uninterrupted, error-free, or
          completely secure. AI-generated content may contain errors. You are responsible
          for reviewing and validating AI outputs before relying on them for business
          decisions.
        </p>
      </section>

      <section>
        <h2>11. Limitation of Liability</h2>
        <p>
          TO THE MAXIMUM EXTENT PERMITTED BY LAW, ORQ8 SHALL NOT BE LIABLE FOR ANY
          INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING
          BUT NOT LIMITED TO LOSS OF PROFITS, DATA, BUSINESS OPPORTUNITIES, OR GOODWILL,
          ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF THE SERVICE.
        </p>
        <p>
          Our total liability for any claims related to the Service shall not exceed the
          amount you paid to us in the twelve (12) months preceding the claim.
        </p>
      </section>

      <section>
        <h2>12. Indemnification</h2>
        <p>
          You agree to indemnify and hold harmless ORQ8, its officers, directors,
          employees, and agents from any claims, losses, damages, liabilities, costs,
          and expenses (including reasonable attorneys&apos; fees) arising out of or
          related to your use of the Service or violation of these Terms.
        </p>
      </section>

      <section>
        <h2>13. Termination</h2>
        <ul>
          <li>You may terminate your account at any time through the Service settings</li>
          <li>We may suspend or terminate your account for violation of these Terms with reasonable notice</li>
          <li>Upon termination, your right to use the Service ceases immediately</li>
          <li>We will provide a reasonable data export period following termination</li>
          <li>Provisions that by their nature should survive termination will survive</li>
        </ul>
      </section>

      <section>
        <h2>14. Governing Law</h2>
        <p>
          These Terms are governed by and construed in accordance with the laws of the
          applicable jurisdiction, without regard to conflict of law principles. Any
          disputes shall be resolved through good-faith negotiation first, then binding
          arbitration if necessary.
        </p>
      </section>

      <section>
        <h2>15. Changes to These Terms</h2>
        <p>
          We may update these Terms from time to time. We will notify you of material
          changes at least 30 days before they take effect. Continued use of the
          Service after changes take effect constitutes acceptance of the updated Terms.
        </p>
      </section>

      <section>
        <h2>16. Contact</h2>
        <p>For questions about these Terms:</p>
        <ul>
          <li><strong>Email:</strong> <a href="mailto:legal@orq8.com">legal@orq8.com</a></li>
        </ul>
      </section>
    </LegalLayout>
  );
}
