import { SettingsShell } from "../../../components/settings-shell";

export const metadata = { title: "Terms & Conditions" };

const sections = [
  {
    h: "The deal",
    body: "ORQ8 is an operating system for your organization. You remain the human in charge: agents act under the authority, approvals, and budget limits you set, and every action is traceable.",
  },
  {
    h: "Agents are not employees",
    body: "Agents are tools you hire within your organization when a business need exists. ORQ8 operates no agent marketplace and takes no commission on agents. What agents do is directed by you and bounded by your constitution.",
  },
  {
    h: "Spending",
    body: "You are responsible for costs generated by the systems you connect and the usage you allow. Budget limits you set are enforced before work proceeds.",
  },
  {
    h: "Billing",
    body: "Every plan starts with 7 days free, card on file, nothing charged until day 8. You can cancel any time.",
  },
];

export default function TermsPage() {
  return (
    <SettingsShell
      title="Terms & conditions"
      description="The operating agreement for your Company of One."
    >
      <div className="max-w-3xl space-y-6 rounded-xl border border-hairline bg-white p-6 sm:p-8">
        {sections.map((s) => (
          <section key={s.h}>
            <h2 className="text-sm font-semibold text-ink">{s.h}</h2>
            <p className="mt-2 text-sm leading-relaxed text-muted">{s.body}</p>
          </section>
        ))}
        <p className="border-t border-hairline pt-5 font-mono text-3xs uppercase tracking-wide text-muted">
          Full legal copy drafts with the beta launch
        </p>
      </div>
    </SettingsShell>
  );
}
